### ISSUE TITLE
Missing Fonos Config

### ISSUE THREAD

**Issue by brunowego** [fonoster/fonoster#216]
**Describe the bug**
When install using Helm Chart, services like `apiserver`, `mediacontroller`, `mediaserver` needs `fonos-config`, that not exists with the current instalation.

```log
Warning  FailedMount  57s (x11 over 7m8s)   kubelet            MountVolume.SetUp failed for volume "fonos-config" : secret "fonos-config" not found
```

**To Reproduce**

```sh
helm install fonoster fonoster/fonos \
  --namespace fonoster-system \
  --version 0.0.7
```

**Screenshots**
<img width="853" alt="Screen Shot 2021-11-10 at 09 07 34" src="https://user-images.githubusercontent.com/441774/141110878-6765b86e-555b-4a4e-8aa9-465998a2340c.png">

**Comment by psanders** [comment]
@brunowego 

We stop supporting K8s a while ago because it was a lot of work and no one was using it. We think that this deserves attention but it would have to be community-driven. 

I will keep this open, but perhaps we should start a [discussion](https://github.com/fonoster/fonoster/discussions) about this topic, so we can create a roadmap for it.

**Comment by psanders** [comment]
Cleanup.
