### ISSUE TITLE
The voice server fails silently if another process is using the same port

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#244]
**Describe the bug**

The voice server fails silently if another process is using the same port

**To Reproduce**

1. Start any process on port 3000
2. Start a voice application on port 3000
3. Observe: The application seems to start without a problem
4. Observe: Fonoster fails to connect to webhook

**Expected behavior**

The voice application should fail with a "port 3000 already in use"

**Screenshots**

NA

**System information (please complete the following):**

 - OS: [e.g. Linux]
 - NodeJS, NPM versions [all]
 - CTL version [0.2.21 ]

**Additional context**

None

**Comment by BrayanMnz** [comment]
When running Rox with another process already using the port 3000. 
There is a "address already in use" message. _see image below_
![image](https://user-images.githubusercontent.com/61812255/167540418-fc6d1efc-0119-40ec-8823-54d75818796d.png)

Is this the expected behaviour or I'm missing something while replicating ? @psanders

**Comment by psanders** [comment]
@BrayanMnz,

Yes. That's the issue. We need to catch the exception and exit with a code 1.

**Comment by efraa** [comment]
@psanders https://github.com/fonoster/rox/pull/8

**Comment by psanders** [comment]
Knowledged.
