### ISSUE TITLE
Some dependencies have pending vulnerability issues

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#299]
**Describe the bug**
We currently depend on some vulnerable packages, including [node-vault ](https://github.com/nodevault/node-vault)and [plugin-warn-if-update-available.](https://github.com/fonoster/plugin-warn-if-update-available)

**To Reproduce**

Install the ctl using `npm install -g @fonoster/ctl` and see the vulnerability notice.

**Expected behavior**
All vulnerable packages should be replaced/updated.

**Additional context**
I traced the issue to the now deprecated packages `request` and `libnpm`. If we find a suitable replacement for both of these libraries, fixing the issue should be straightforward.

**Comment by BrayanMnz** [comment]
If I right understand, request and libnpm are the root causes. 

After validating some options the two finals alternatives are: 

- [axios](https://github.com/axios/axios) :

Everyone maybe knows what is _axios_. Axios is well documented, actively maintained and currently out of vulnerability per snyk.io [results ](https://snyk.io/test/npm/axios)
     
- got : 

got is actually consider one of the best alternatives to request and is being currently mantained. They actually got a [comparison table ](https://github.com/sindresorhus/got/blob/main/documentation/migration-guides/request.md) and a [migration guide](https://github.com/sindresorhus/got/blob/main/documentation/migration-guides/request.md) from _request_ to _got_ 

got is actually out of vulnerability per snyk.io [results](https://snyk.io/test/npm/got)


I'd rather Axios because all of its background but we also should consider **_got_**  What do you think @psanders

**Comment by psanders** [comment]
@BrayanMnz 

You are correct those two packages do root. The challenge is that they are transitive dependencies which makes them a bit difficult to replace. The issue must be fixed at [node-vault](https://github.com/nodevault/node-vault) and [plugin-warn-if-update-available.](https://github.com/fonoster/plugin-warn-if-update-available). 

The package node-vault has a [PR](https://github.com/nodevault/node-vault/pull/151) to replace Request with Axios, but no action has been taken. At this point, I am inclined to fork both packages and fix the issue until the maintainers of those projects get up to date.

**Comment by nisancigokmen** [comment]
@psanders  🎸

**Comment by psanders** [comment]
Note to self:

Consider replacing `node-vault` with https://www.npmjs.com/package/hashi-vault-js

**Comment by psanders** [comment]
Fixed.
