### ISSUE TITLE
Operator: Docker Swarm

### ISSUE THREAD

**Issue by alifiratari** [fonoster/fonoster#380]
Is your feature request related to a problem? Please describe.
It does not have HA(High Availability) feature.

Describe the solution you'd like
Adding a new operator for docker swarm.

Describe alternatives you've considered
Adding a new operator for kubernetes.

**Comment by psanders** [comment]
@alifiratari 👋

We could create a `community-operators` repo to consolidate all the operators (including Docker-Compose and Swarm). 

Since Docker, Inc. has slowed down its push for Swarm is unlikely we will focus on it. However, we will be happy to accept/support community contributions. 

Another option is to work on K8s support. Since it is already on the [roadmap](https://github.com/orgs/fonoster/projects/9/views/1), we could sync our efforts.

What do you think?

**Comment by YuriCodes** [comment]
Hello @alifiratari, can you report the status on this?

**Comment by psanders** [comment]
It seems this got very cold. Closing for now, but feel free to re-open.
