### ISSUE TITLE
Write "Hello World" guide

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#405]
### Summary

Write a guide covering the typical "Hello World."

### Intended Outcome

Users can signup for an account and complete the "Hello World."

### Definition of Done (DoD)

When:

- [ ] The guide is peer-reviewed 
- [ ] A non-team member can complete the guide (Someone from the community?)
- [ ] The guide is published at [learn](https://learn.fonoster.com )

**Comment by efraa** [comment]
@psanders, consider updating [Create User Account Guide](https://learn.fonoster.com/docs/getting_started/create_an_user_account) on this task.

**Comment by psanders** [comment]
Good catch. Will do.

**Comment by psanders** [comment]
Related PR:

https://github.com/fonoster/website/pull/5

**Comment by efraa** [comment]
@YuriCodes 

- Update ngrok command to `npm install -g ngrok` so that it is installed as a global dependency and can be used from any path on your machine.

- Why do we need to install `cross-env`? It seems to me that it was already added as a dev-dependency.

**Comment by efraa** [comment]
@YuriCodes 

What do you think about adding the "Create an User Account" guide as a dependency so you can remove the section where you tell how to create a Project?

**Comment by efraa** [comment]
@YuriCodes 

What do you think about adding the "Create an User Account" guide as a dependency so you can remove the section where you tell how to create a Project?

**Comment by YuriCodes** [comment]
@efraa 
> * Update ngrok command to `npm install -g ngrok` so that it is installed as a global dependency and can be used from any path on your machine. 
> * Why do we need to install `cross-env`? It seems to me that it was already added as a dev-dependency.

Good idea! Also it just doesn't seem to work doing npm i for some reason. If an user is just stumbling upon that guide it is best they install it separately. I did so during the YT video too 

> What do you think about adding the "Create an User Account" guide as a dependency so you can remove the section where you tell how to create a Project?

Most of the time when people go to a 'Hello World' doc they expect to have all they need to do so in that tutorial,  the goal is to guide the user who is curious how to do it from 'zero to hero' without them having to move around so much since that would be their first time playing around with Fonoster. If you feel like it is repetitive we could do it, have one as 'Hello World' and then send them to a 'next step' page or something where the create a Project is. I'd think of it more like a tutorial instead of a how-to like the Create an User Account is

**Comment by psanders** [comment]
Closing in favor of https://github.com/fonoster/internal-board/issues/12
